### ISSUE TITLE
Create 'uses' page

### ISSUE THREAD

**Issue by MichaelDeBoey** [driesvints/driesvints.com#36]
Like you asked, this is my request to add a 'uses' page on your website where we can have a look at all the software/hardware you're using.

Some examples:
- @wesbos: https://wesbos.com/uses
- @kentcdodds: https://kentcdodds.com/uses
- @adamwathan: https://adamwathan.me/uses
- @freekmurze: https://freek.dev/uses

**Comment by driesvints** [comment]
I'm probably not going to make such a page any time soon, sorry.
