### ISSUE TITLE
Update information about dark mode .SVG's in github readme

### ISSUE THREAD

**Issue by swissbuechi** [driesvints/driesvints.com#76]
[Blogpost](https://driesvints.com/blog/investigating-dark-mode-for-svgs-in-github-readmes)

There is now acctually a clean way to achieve this: [https://youtu.be/jHr6Pc8oQjM](https://youtu.be/jHr6Pc8oQjM)

Maybe you want to update your post.

Thanks a lot.

**Comment by swissbuechi** [comment]
Just saw you already updated the solution.

Sorry, you can close this issue.

**Comment by driesvints** [comment]
Hey @swissbuechi, I now also added the solution from GitHub itself: https://github.blog/changelog/2021-11-24-specify-theme-context-for-images-in-markdown/

Thanks!
